name: yelp_fusion_client
version: 0.2.0+3-hotfix

description: A Dart Client to access the business endpoints of Yelp Fusion API.
homepage: https://github.com/HelloFro/yelp_fusion_client

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  http: ^0.13.4
  envify: ^2.0.2

dev_dependencies:
  test: ^1.20.1
  envify_generator: ^2.0.2
  build_runner: ^2.1.5