name: yelp_fusion_client
version: 0.1.0

description: A Dart Client to access the endpoints of Yelp Fusion API.
homepage: https://github.com/HelloFro/yelp_fusion_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  http: ^0.13.0
  meta: ^1.3.0