name: yelp_fusion_client
description: A new Flutter package project.
version: 0.0.1
author: HelloFro (Fro Warner)
homepage: https://github.com/HelloFro/yelp_fusion_client

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter