name: yelp_fusion_client
description: A Dart Client to access the endpoints of Yelp Fusion API.
version: 0.0.1
author: HelloFro (Fro Warner)
homepage: https://github.com/HelloFro/yelp_fusion_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.0
  meta: ^1.3.0